# Generated by Django 5.1.2 on 2024-12-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather_conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('climate_description', models.CharField(max_length=30)),
                ('humidity_indices', models.FloatField()),
                ('wind_pressure', models.CharField(max_length=30)),
                ('chance_of_rain', models.FloatField()),
            ],
        ),
    ]
