# Generated by Django 5.1.2 on 2024-12-11 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather_conditions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beehive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=30)),
                ('open_brood_frames', models.IntegerField()),
                ('capped_brood_frames', models.IntegerField()),
                ('queen_presence', models.BooleanField()),
                ('queen_color', models.CharField(max_length=15)),
                ('origin', models.CharField(max_length=20)),
                ('food_frames', models.IntegerField()),
                ('observations', models.CharField(max_length=90)),
                ('qr_code', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=30)),
                ('id_weather_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_conditions.weather_conditions')),
            ],
        ),
    ]
