# Generated by Django 5.1.2 on 2024-12-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='date_signup',
            new_name='date_login',
        ),
    ]
